POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "Boards of Canada",
    "genre": "Electronic",
    "albums": [
        {
            "title": "Tomorrow's Harvest",
            "release_date": "2013-01-01"
        },
        {
            "title": "Music Has the Right to Children",
            "release_date": "1998-04-20"
        }
    ]
}

###
GET http://localhost:8000/bands?genre=electronic&has_albums=false