POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "Boards of Canada",
    "genre": "ELECTRONIC",
    "albums:": [
        {
            "title": "Music Has the Right to Children",
            "release_date": "1998-04-20"
        },
        {
            "title": "Geogaddi",
            "release_date": "2002-10-07"
        }
    ]   
}

###
GET http://localhost:8000/bands?genre=electronic&has_albums=false