POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "Whizzbang Music",
    "genre": "electronic",
    "albums:": [
        {
            "title": "Fruitcake bonanza",
            "release_date": "2013-01-01"
        }
    ]   
}

###
GET http://localhost:8000/bands/22
